# (c) Copyright 2019 Hewlett Packard Enterprise Development LP
#
version: 2.1

jobs:
  terraform-plan:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout

      - setup_remote_docker:
          # See https://circleci.com/docs/2.0/building-docker-images/#docker-version
          # for available versions
          version: 18.09.3

      - run:
          name: run terraform plan
          command: |
            terraform init
            terraform plan

  terraform-apply:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout

      - setup_remote_docker:
          # See https://circleci.com/docs/2.0/building-docker-images/#docker-version
          # for available versions
          version: 18.09.3

      - run:
          name: run terraform apply
          command: |
            terraform init
            terraform apply -f

workflows:
  check:
    jobs:
      - terraform-plan:
          context: devtest

  merge_to_master:
    jobs:
      - terraform-apply:
          filters:
            branches:
              only: master
          context: devtest
